services:
  - type: web
    name: django-notes-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn notes_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: notes_project.settings
      - key: PYTHON_VERSION
        value: 3.10
